config/routes.rb
DominionStrategyClone::Application.routes.draw do
  root to: 'static_pages#root'
  resources :users
  resource :session
  resources :replies, only: [:show, :edit, :update, :destroy]
  resources :boards do
    resources :topics, only: [:new, :create]
  end
  resources :topics, only: [:show, :edit, :update, :destroy] do
    resources :replies, only: [:new, :create]
  end
  namespace :api, defaults: { format: :json } do
    resources :notifications, only: [:show, :index, :create, :update]
    resources :users
    resources :replies, only: [:show, :edit, :update, :destroy]
    resources :boards do
      resources :topics, only: [:new, :create]
    end
    resources :topics, only: [:show, :edit, :update, :destroy, :index, :create] do
      resources :replies, only: [:new, :create, :edit]
    end
    resources :replies
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :user_id, presence: true
  validates :title, presence: true
  validates :body, presence: true

  belongs_to(
      :user,
      :class_name => "User",
      primary_key: :id,
      foreign_key: :user_id
  )
  belongs_to(
      :board,
      :class_name => "Board",
      primary_key: :id,
      foreign_key: :board_id
  )
  has_many(
    :replies,
    :class_name => "Reply",
    primary_key: :id,
    foreign_key: :topic_id
    )
end

app/controllers/api/topics_controller.rb
class Api::TopicsController < ApplicationController

  before_filter :reguire_login, except: [:index, :show]

  def index
    @topics = Topic.all
    render :json => @topics
  end
  def show
    @topic = Topic.find(params[:id])
    render :show
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      render :json => @topic
    else
      render :json => @topic.errors.full_messages, status: 422
    end
  end

  def destroy
    Topic.find(params[:id]).destroy
    @topics = Topic.all
    render :json => "topic destroyed"
  end

  def update
    @topic = Topic.find(params[:id])
    if @topic.update_attributes(topic_params)
      render :json => @topic
    else
      render :json => @topic.errors.full_messages, status: 422
    end
  end

  def topic_params
    params.require(:topic).permit(:title,:body,:user_id,:board_id)
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_filter :reguire_login, except: [:index, :show]

  def index
  end

  def new
    @topic = Topic.new
    render :new
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      redirect_to(topic_url(@topic))
    else
      flash.now[:errors] = @topic.errors.full_messages
      render :new
    end
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def destroy
    @topic = Topic.find(params[:id])
    @board = @topic.board
    @topic.destroy
    redirect_to(board_url(@board))
  end

  def edit
    @topic = Topic.find(params[:id])
    if current_user.id == @topic.user_id
      render :edit
    else
      redirect_to boards_url
    end
  end

  def update
    @topic = Topic.find(params[:id])
    if @topic.update_attributes(topic_params)
      redirect_to topic_url(@topic)
    else
      flash.now[:errors] = @topic.errors.full_messages
      render :edit
    end
  end

  def topic_params
    params.require(:topic).permit(:title,:body,:user_id,:board_id)
  end
end

app/views/topics/edit.html.erb
Board: <%= @topic.board.title %><br>

<form action="<%= topic_url(@topic) %>" method="post">
  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="put">

Change Title? <input type="text" value="<%= @topic.title %>" name="topic[title]"><br><br>
Change Content? <br><textarea rows="12" cols="80" value="<%= @topic.body %>" name="topic[body]"></textarea><br>
<input type="submit" value="update topic">
</form>

app/views/topics/new.html.erb
<h1><%= Board.find_by_id(params[:board_id]).title %></h1>
<h1> Start new topic </h1>
<form action="<%= board_topics_url%>" method="post">
    <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>"><br>
    <label> Title
<input type="text" name="topic[title]" value="<% @topic.title %>">
    </label><br><br>
    <label> Body <br>
<textarea rows="12" cols="80" name="topic[body]" value="<% @topic.body %>"></textarea>
    </label><br>
<input type="hidden" name="topic[user_id]" value="<%= current_user.id %>">
<input type="hidden" name="topic[board_id]" value="<%= params[:board_id] %>">
<input type="submit" value="post">
</form>

app/views/topics/show.html.erb
<style>

  .container {
    width: 100%;
    padding: 10px;
  }
  .board {
    display: block;
    font-size: 180%;
    margin: auto;
    width: 330px;
    border-bottom: 2px solid blue;
  }
  .topic {
    font-size: 230%;
    width: 100%;
    margin: auto;
  }
  .reply-data {
    width: 100%;
  }
  .reply-content {
    overflow: scroll;
    display: block;
    padding: 2px;
    width: 700px;
    float: left;
    height: 100px;
    background: #DFF0AF;
  }

  .parent {
    width: 100%;
  }
  .author {
    float: left;
    width: 100px;
    background: #A8F9FD;
  }
  .reply {
    width: 100%;
  }
  .reply-links: {
    display: block;
    background: solid blue;
    align: right;

  }
  .group:after {
    content: "";
    clear: both;
  }


</style>

<div class="container group">
<div class="board"> Board: <%= link_to(@topic.board.title, board_url(@topic.board)) %> </div><br>
<div class="topic"> Topic: <%= @topic.title %></div>
</div>


<br>

<ul class="parent">
 <li class="reply">
   <ul class="reply-data">

       <% if @topic.user != nil %>
       <li class="author">Author:
         <%= link_to(@topic.user.username, user_url(@topic.user)) %>
       </li>
      <% else %>
      <li class="author">
        The author of this topic has deleted their profile
      </li>
      <% end %>
      <div class="reply-content">
        <li class="content">
           <%= @topic.body %>
        </li>
      </div>
      <% if current_user && @topic.user_id == current_user.id %>
        <div class="reply-links">
          <form action="<%= topic_url(@topic) %>" method="post">
            <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
            <input type="hidden" name="_method" value="delete">
            <li>
                <input type="submit" value="remove topic" class="submit">
            </li>
          </form>
            <li>
              <%= link_to("edit topic", edit_topic_url(@topic)) %>
            </li>
        </div>

      <% end %>
    </ul>
  </li>
<% @topic.replies.each do |reply|%>
<li class="reply">
<ul class="reply-data">
  <% if reply.user != nil %>
     <li class="author">Author: <%= link_to(reply.user.username, user_url(reply.user)) %></li>
  <% else %>
     <li class="author">the author of this reply has deleted their profile</li>
  <% end %>
   <div class="reply-content">
     <li class="content">
       <%= reply.content %>
     </li>
   </div>
    <% if current_user && reply.user_id == current_user.id %>
    <div class="reply-links">
      <form action="<%= reply_url(reply) %>" method="post">
        <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="delete">
        <li><input type="submit" value="remove reply" class="submit"></li>
      </form>
      <li><%= link_to("edit reply", edit_reply_url(reply)) %></li>
    </div>

  <% end %>
  </ul>
</li>
<% end %>
</ul>
<% if logged_in %>
  <%= link_to("Post Reply", new_topic_reply_url(@topic.id)) %>
<% end %>