config/routes.rb
DominionStrategyClone::Application.routes.draw do
  root to: 'static_pages#root'
  resources :users
  resource :session
  resources :replies, only: [:show, :edit, :update, :destroy]
  resources :boards do
    resources :topics, only: [:new, :create]
  end
  resources :topics, only: [:show, :edit, :update, :destroy] do
    resources :replies, only: [:new, :create]
  end
  namespace :api, defaults: { format: :json } do
    resources :notifications, only: [:show, :index, :create, :update]
    resources :users
    resources :replies, only: [:show, :edit, :update, :destroy]
    resources :boards do
      resources :topics, only: [:new, :create]
    end
    resources :topics, only: [:show, :edit, :update, :destroy, :index, :create] do
      resources :replies, only: [:new, :create, :edit]
    end
    resources :replies
  end
end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
  include BCrypt
  validates :username, :session_token, :password_digest, presence: true
  validates :password, length: {minimum: 5, allow_nil: true}
  validates :username, uniqueness: true

  after_initialize do |user|
      user.set_session_token
  end
  has_many(
      :boards,
      :class_name => "Board",
      primary_key: :id,
      foreign_key: :admin_id
    )
    has_many(
        :topics,
        :class_name => "Topic",
        primary_key: :id,
        foreign_key: :user_id
    )
    has_many(
      :replies,
      :class_name => "Reply",
      primary_key: :id,
      foreign_key: :user_id
    )
    has_many(
      :notifications,
      :class_name => "Notification",
      primary_key: :id,
      foreign_key: :user_id
    )

  def set_session_token
    self.session_token ||= generate_session_token
  end
  def generate_session_token
    return SecureRandom.urlsafe_base64
  end
  def password
    @password
  end
  def password=(password)
    psword = Password.create(password)
    self.password_digest = psword
    @password = password
  end
  def is_password?(password)
    Password.new(self.password_digest) == password
  end
  def self.find_by_credentials(username,password)
    user = User.find_by_username(username)
    if user && user.is_password?(password)
      return user;
    else
      return nil
    end
  end
  def reset_session_token
    self.set_session_token
    self.save
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  def index
    @users = User.all
    render :json => @users
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :reguire_login, except: [:new, :create, :show]
  before_filter :require_logout, only: [:new, :create]

  def index
    @users = User.all
    render :index
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    @user.admin = false
    if @user.save
      login(@user)
      redirect_to('/#')
    else
      if @user.password.length == 0
        flash.now[:errors] = "Password field empty"
      else
        flash.now[:errors] = @user.errors.full_messages
      end
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find_by_id(params[:id])
    if (@user == current_user) || (current_user.admin)
      render :edit
    else
      redirect_to(boards_url)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      if current_user.admin && (params[:admin] == "true")
        @user.update_attributes(admin: true)
      end
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to("#")
  end

  def user_params
    params.require(:user).permit(:username,:password)
  end
end

app/views/users/edit.html.erb
<form action="<%= user_url%>" method="post">
  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="put">
Change Username<input type="text" value="<%= @user.username %>" name="user[username]">
  <input type="submit" value="update user">
  <% if (current_user.admin && !@user.admin) %>
    <label>
    <input type="radio" name="admin" value="false" class="radio">
    <%= @user.username %> is not an Admin
    <label>
      <br>
      <label>
    <input type="radio" name="admin" value="true" class="radio">
    Make <%= @user.username %> an Admin
  </label>
  <% end %>
</form>

app/views/users/index.html.erb
<h1>Index</h1>
<ul>
  <% @users.each do |user| %>
  <div class="topic-container">
  <li class="topic"> <%= link_to(user.username, user_url(user)) %>
  </li>
  </div>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up </h1>
<form action="<%= users_url %>" method="post">
  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
  <label>Username
  <input type="text" name="user[username]" value="<%= @user.username %>">
  </label>
  <label>Choose password
  <input type="password" name="user[password]">
  </label>
  <input type="submit" value="Register" class="submit">


</form>

app/views/users/show.html.erb
<style>
.topic {
  width: 500px;
}

.topic-container {
  height: 75px;
}
</style>

<h1><%= @user.username %>'s Profile Page!</h1>

<% if @user.admin %>
<%= @user.username %> is an admin
<% else %>
<%= @user.username %> is not an admin
<% end %>
<%= "#{@user.username} has posted #{@user.topics.count} topics, and #{@user.replies.count} replies" %>

<br>
<% if @user.topics.length != 0 %>

  <%= @user.username %>'s topics
  <ul>
    <% @user.topics.each do |topic| %>
<li class="topic-container">
  <div class="topic"><%= link_to(topic.title, '/#topics/' + topic.id.to_s) %>
  </div>
  </li>

</ul>
  <% end %>
<% else %>
    <%= @user.username %> has no topics yet
<% end %>

<% if @user == current_user %>
  <%= link_to("edit your profile", edit_user_url(@user.id)) %>
<% end %>
<% if (current_user && current_user.admin) && !@user == current_user  %>
  <%= link_to("edit this profile", edit_user_url(@user.id)) %>
<% end %>
<% if current_user && (@user == current_user || current_user.admin) %>
  <form action="<%= user_url(@user) %>" method="post">
  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="delete profile" class="submit">
</form>

<% end %>