config/routes.rb
DominionStrategyClone::Application.routes.draw do
  root to: 'static_pages#root'
  resources :users
  resource :session
  resources :replies, only: [:show, :edit, :update, :destroy]
  resources :boards do
    resources :topics, only: [:new, :create]
  end
  resources :topics, only: [:show, :edit, :update, :destroy] do
    resources :replies, only: [:new, :create]
  end
  namespace :api, defaults: { format: :json } do
    resources :notifications, only: [:show, :index, :create, :update]
    resources :users
    resources :replies, only: [:show, :edit, :update, :destroy]
    resources :boards do
      resources :topics, only: [:new, :create]
    end
    resources :topics, only: [:show, :edit, :update, :destroy, :index, :create] do
      resources :replies, only: [:new, :create, :edit]
    end
    resources :replies
  end
end

app/models/board.rb
class Board < ActiveRecord::Base
  validates :title, presence: true
  validates :admin_id, presence: true
  belongs_to(
      :user,
      :class_name => "User",
      primary_key: :id,
      foreign_key: :admin_id
  )
  has_many(
      :topics,
      :class_name => "Topic",
      primary_key: :id,
      foreign_key: :board_id,
      dependent: :destroy
  )
end

app/controllers/api/boards_controller.rb
class Api::BoardsController < ApplicationController

  before_filter :reguire_login, except: [:index, :show]
  before_filter :require_admin, except: [:index, :show]

  def index
    @boards = Board.all
    render :json => @boards
  end

  def show
    @board = Board.find(params[:id])
    render :show
  end

  def create
    @board = Board.new(board_params)
    if @board.save
      render :json => @board
    else
      render :json => @board.errors.full_messages, status: 422
    end
  end

  def destroy
    Board.find(params[:id]).destroy
    @boards = Board.all
    render :json => "board destroyed"
  end

  def update
    @board = Board.find(params[:id])
    if @board.update_attributes(board_params)
      render :json => @board
    else
      render :json => @board.errors.full_messages, status: 422
    end
  end

  def board_params
    params.require(:board).permit(:title, :admin_id)
  end

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  before_filter :reguire_login, except: [:index, :show]
  before_filter :require_admin, except: [:index, :show]

  def index
    @boards = Board.all
    render :index
  end

  def new
    @board = Board.new
    render :new
  end

  def create
    @board = Board.new(board_params)
    if @board.save
      redirect_to(boards_url)
    else
      flash.now[:errors] = @board.errors.full_messages
      render :new
    end
  end

  def show
    @board = Board.find(params[:id])
    render :show
  end

  def destroy
     Board.find(params[:id]).destroy
     @boards = Board.all
     render :index
  end

  def edit
    @board = Board.find(params[:id])
    render :edit
  end

  def update
    @board = Board.find(params[:id])
    if @board.update_attributes(board_params)
      redirect_to(boards_url)
    else
      flash.now[:errors] = @topic.errors.full_messages
      render :edit
    end
  end

  def board_params
    params.require(:board).permit(:title, :admin_id)
  end

end

app/views/boards/edit.html.erb
<form action="<%= board_url(@board.id)%>" method="post">
<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="put">
Title :<input type="text" value="<%= @board.title %>" name="board[title]">
<input type="submit" value="update board title">
</form>

app/views/boards/index.html.erb
<style>
  .change {
    float: right;
    display: block;
    background: red;
  }
</style>

<h1> Home </h1>
<ul>
  <% @boards.each do |board| %>
  <li class="topic-container"> <div class="topic"> <%= link_to(board.title, board_url(board)) %></div>
    <% if current_user && current_user.admin %>
    <form action="<%= board_url(board) %>" method="post">
        <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="delete">
        <div class="change">
          <input type="submit" value="REMOVE">
        </div>
    </form>
    <div class="change">
      <%= link_to("EDIT BOARD", edit_board_url(board)) %>
    </div>

    <% end %>
  </li>
  <% end %>
</ul>

app/views/boards/new.html.erb
<h1> Start New Board </h1>

<form action="<%= boards_url %>" method="post">
  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
<label> Title
<input type ="text" name="board[title]">
</label>
<input type ="hidden" value="<%= current_user.id %>" name="board[admin_id]">
<input type="submit" value="Create Board">

</form>

app/views/boards/show.html.erb
<style>
  .new-topic {
    background: #D6D5DB;
    padding: 4px;
    display: block;
    margin: auto;
    width: 75px;
  }
  .new-topic-container {
    width: 100%;
    height: 75px;
    padding: 22px;
  }
</style>

<h1> <%= @board.title %> </h1>

<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
  </tr>
<% @board.topics.each do |topic| %>
   <tr> <td><%= link_to(topic.title, topic_url(topic)) %></td>
     <% if topic.user != nil%>
       <td><%= link_to(topic.user.username, user_url(topic.user)) %></td>
     <% else %>
       <td>The author of this Topic has deleted their profile</td>
     <% end %>
   </tr>
<% end %>
</table>
<% if logged_in %>
<div class="new-topic-container">
<%= link_to("New Topic", new_board_topic_url(@board), class: "new-topic") %>
</div>
<% end %>