config/routes.rb
DominionStrategyClone::Application.routes.draw do
  root to: 'static_pages#root'
  resources :users
  resource :session
  resources :replies, only: [:show, :edit, :update, :destroy]
  resources :boards do
    resources :topics, only: [:new, :create]
  end
  resources :topics, only: [:show, :edit, :update, :destroy] do
    resources :replies, only: [:new, :create]
  end
  namespace :api, defaults: { format: :json } do
    resources :notifications, only: [:show, :index, :create, :update]
    resources :users
    resources :replies, only: [:show, :edit, :update, :destroy]
    resources :boards do
      resources :topics, only: [:new, :create]
    end
    resources :topics, only: [:show, :edit, :update, :destroy, :index, :create] do
      resources :replies, only: [:new, :create, :edit]
    end
    resources :replies
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>DominionStrategyClone</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="pageheadborder">
  <div class="pagehead">
  <div class="top">
<h1>Dominion Strategy Forum</h1>
  </div>
<div id="errors">
  <%= flash[:errors] %>
</div>


<div class="hello">
<% if logged_in %>
  <%= "Hello #{current_user.username} "%>
<% else %>
  Welcome, Guest
<% end %>
</div>


<% if current_user && current_user.notifications.select{|n| n.is_read == false}.length != 0 %>
  <div id="notifications" class="notifications">
    <%= link_to("Show new replies to your posts.",'/#/notifications') %>
  </div>
<% end %>
</div>
</div>



<div class="group">

<ul class="nav-bar group">
  <li class="nav home">
    <a href="/#">HOME</a>
  </li>
<% if logged_in %>
  <li class="nav">
  <form action="<%= session_url %>" method="POST">
    <input type="hidden" name="_method" value="DELETE">
    <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

    <input type="submit" value="LOGOUT" class="submit">
  </form>
</li>


  <li class="nav">
  <%= link_to("MEMBERS", users_url) %>
  </li>

  <li class="nav">
    <%= link_to("PROFILE", user_url(current_user))%>
  </li>

  <% if current_user.admin %>

  <li class="nav">
    <%= link_to('CREATE BOARD', '/#boards/new' ) %>
  </li>

  <% end %>

<% else %>

 <li class="nav">
   <%= link_to('REGISTER', new_user_url) %>
 </li>

 <li class="nav">
   <%= link_to('LOGIN', new_session_url) %>
 </li>

<% end %>
</ul>

</div>
<div class="main-content">
<%= yield %>
</div>

</body>
</html>